### ISSUE TITLE
Release 0.6.1 - Tar.gz download missing

### ISSUE THREAD

**Issue by Zennoe** [abelcheung/rifiuti2#11]
Only the asc file was uploaded but the tar.gz is nowhere to be found: https://github.com/abelcheung/rifiuti2/releases

**Comment by abelcheung** [comment]
Sorry for confusion, the tar/gz archive is referring to the one automatically generated by Github, that is the "`Source code (tar.gz)`" link. I will clarify it in the future (if motivated to push newer releases :smile: )
